### PR TITLE
Update to feathers 3.0

### PR DESCRIPTION
**Pull request by tiagosantos967**
Dear kozzztya,

Thank you so much for your contribution to the feathers community. This project makes the integration between feathers and RabbitMQ really simple.

I noted that the current version is not compatible with the latest version of feathers, so I took the initiative to upgrade it. 

I kindly ask you to consider the pull request and merge it with the production branch of the library.

Best,
Tiago

### CODE REVIEW

**Comment by kostia-official** [comment]
@tiagosantos967 Thank you for your contribution! Can you please also update the readme and I'll merge it?

**Comment by tiagosantos967** [comment]
@kozzztya The readme was already changed. I changed the usage, the rest is still the same. Or are you asking for something specific?

**Comment by kostia-official** [comment]
Nothing specific. Then, everything is great! I'll publish it today.

**Comment by kostia-official** [comment]
@tiagosantos967 I've published it:
https://www.npmjs.com/package/feathers-amqp-events-publish/v/1.0.0 
Please, test.

**Comment by tiagosantos967** [comment]
Tested. Working as expected

**Pull request merged**
