### PR TITLE
Adding features to allow and ignore specific services

### PR DESCRIPTION
**Pull request by tiagosantos967**
Hi @kozzztya ,

In my team we have a high number of services and we don't need / want to publish all of them.

This pull request adds 2 features:
- allowing only specific services to be published to RabbitMQ
- ignoring specific services to be published to RabbitMQ

Please consider the new features for the library.

Thanks,
Tiago

### CODE REVIEW

**Comment by kostia-official** [comment]
@tiagosantos967 Thank you for your contribution. It looks like a good idea. 
What do you think about using `filter` and `reject` lodash functions for cleaner code?

**Comment by tiagosantos967** [comment]
@kozzztya thanks for the feedback. 
Changes have been made. 

Decided to go for the `pickBy` since `app.services` is not an array of jsons, where `filter` and `reject` make more sense to use.

Or are you did you envision it another way?

**Comment by kostia-official** [comment]
Hi! Sorry, I don't have enough time for reviewing this PR. Everything looks great. Could you just bump a version to 1.1.0 and I'll publish it.

**Comment by tiagosantos967** [comment]
Done! Thanks

**Pull request merged**
